### ISSUE TITLE
What about add `tzdata` to (alpine) image?

### ISSUE THREAD

**Issue by bscheshirwork** [docker-library/redis#138] opened 2018-04-18 09:32 UTC
I have service in the composition who can set timezone with
```yml
    environment:
      TZ: Europe/Moscow
```
redis image should extend `tzdata`?

```dockerfile
&& apk add --no-cache tzdata \
```

**Comment by yosifkit** [comment] 2018-04-19 20:51
Technically a duplicate of #127 (but that was closed before any discussion).

As far as I can tell the redis server does not concern itself with time zones and only uses and returns unix timestamps.

**Comment by bscheshirwork** [comment] 2018-04-20 11:49
Any logs on this container? Ok. Typically I will to expect see "synchronized" logs on all of related containers...

**Comment by tianon** [comment] 2018-04-20 16:35
Confirmed, setting `TZ` adjusts the logging timestamps in `redis:latest` but not in `redis:alpine`. :disappointed:

**Closed** 2018-09-04 21:05 UTC
Labels: Issue
