### ISSUE TITLE
Redis 7.0.11 (latest): Fatal Can't initialize Background Jobs

### ISSUE THREAD

**Issue by flaushi** [docker-library/redis#366] opened 2023-06-22 05:14 UTC
it seems like 7.0.11 was tagged `latest` lately.
I cannot bring up the service, seemingly on all debian buster hosts, still analyzing there.
My setup is fairly standard:
my docker-compose.yml merely states:
```
version: '2'

services:

    redis:
        image: redis:latest
        restart: unless-stopped
```

**Comment by Uranium2** [comment] 2023-06-22 11:41
Same

**Comment by yosifkit** [comment] 2023-06-22 17:01
Duplicate of #365; see https://github.com/docker-library/redis/issues/365#issuecomment-1599633849

**Closed by yosifkit** 2023-06-22 17:01 UTC
