### ISSUE TITLE
Can redis set environment variables like MySQL

### ISSUE THREAD

**Issue by jin10086** [docker-library/redis#113] opened 2017-12-01 14:33 UTC
like 
```docker
  dbmaster:
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: example
  dbslave:
    image: redis
    restart: always
    environment:
      MASTERPASS:example
```
the i can run redis cluster very quickly

I wanted to do it myself. but I'm bad at shell...

**Comment by leezzxuan** [comment] 2018-01-29 06:30
have you get the solution? I've got the same problem

**Comment by yosifkit** [comment] 2018-01-29 18:16
Closing as duplicate of #46.  There are [solutions](https://github.com/docker-library/redis/issues/46#issuecomment-211598784) discussed [there](https://github.com/docker-library/redis/issues/46#issuecomment-335326234).

**Closed by yosifkit** 2018-01-29 18:16 UTC
