### ISSUE TITLE
Is there a way to turn on clustered mode?

### ISSUE THREAD

**Issue by craigpastro** [docker-library/redis#395] opened 2024-03-21 00:11 UTC
I want to use a Redis test container with clustered mode on to test my service, but I haven't found any nice way to do this. Do you know of any?

Unlike the `redis/redis-stack` image, this image does not seem to use the `REDIS_ARGS` environment variable. I suppose if it did, I could do something like:
```
docker run --rm --name redis -e REDIS_ARGS="--cluster-enabled yes" redis
```

Anyway, I appreciate any help. Thank you!

**Comment by yosifkit** [comment] 2024-03-21 17:43
Args to `redis-server` can just be passed in on the docker command line (anything after the image):

```console
$ docker run --rm --name redis redis --cluster-enabled yes
```

**Comment by tianon** [comment] 2024-03-21 22:05
Also, duplicate of https://github.com/docker-library/redis/issues/30 :sweat_smile:

**Closed by tianon** 2024-03-21 22:05 UTC

**Comment by craigpastro** [comment] 2024-03-22 02:43
Thanks @yosifkit! That's very helpful to know.
