### ISSUE TITLE
Wrong date in docker container

### ISSUE THREAD

**Issue by cdupont** [docker-library/redis#290] opened 2021-09-06 17:06 UTC
I'm running redis:6.0-alpine on Raspberry PI.
I noticed a wrong date in the container:
```
pi@raspberry:~ $ docker exec -it redis date
Thu May  7 02:52:32 UTC 2071
pi@raspberry:~ $ date
Mon Sep  6 19:04:41 CEST 2021
```

I just pull it and run it:
```
$ docker run redis:6.0-alpine
Unable to find image 'redis:6.0-alpine' locally
6.0-alpine: Pulling from library/redis
...
1:M 04 May 2071 17:40:24.000 # Server initialized
1:M 04 May 2071 17:40:24.000 * Ready to accept connections
```

This causes problems with some Redis commands.

**Comment by wglambert** [comment] 2021-09-07 17:05
I'm not able to reproduce
```console
$ date
Tue Sep  7 17:03:27 UTC 2021

$ docker run -it --rm redis:6.0-alpine ash
Unable to find image 'redis:6.0-alpine' locally
6.0-alpine: Pulling from library/redis
a0d0a0d46f8b: Pull complete 
a04b0375051e: Pull complete 
cdc2bb0f9590: Pull complete 
d0892b8dbfbb: Pull complete 
2708df91552a: Pull complete 
a57392b26282: Pull complete 
Digest: sha256:61f3e955fbef87ea07d7409a48a48b069579e32f37d2f310526017d68e9983b7
Status: Downloaded newer image for redis:6.0-alpine

/data # date
Tue Sep  7 17:03:32 UTC 2021
```

See also https://github.com/docker-library/redis/issues/138

**Comment by cdupont** [comment] 2021-09-07 17:55
It's related to this problem: https://stackoverflow.com/questions/66091978/corrupt-date-with-redis6-alpine-on-raspi
https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/
It seems to be caused by an outdated version of `libseccomp` in Raspbian.
It affects branches 5 and 6 of Redis (watch the date):
```
$ docker run -p 6379:6379 redis:5-alpine
1:C 20 Jun 2071 21:46:48.000 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
pi@wazigate:~ $ docker run redis:6.0-alpine
1:C 10 May 2071 23:51:36.000 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
```
Older versions are fine:
```
pi@wazigate:~ $ docker run redis:6.0.6-alpine3.12
1:C 07 Sep 2021 08:01:42.756 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
```

**Comment by tianon** [comment] 2021-09-07 20:32
Yep, this is completely expected; see https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements

You might also run into https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2

**Comment by tianon** [comment] 2021-09-07 20:32
(Closing since it's not something we can fix in the image -- it's something that has to be fixed on your container host.)

**Closed by tianon** 2021-09-07 20:32 UTC
Labels: question
