### ISSUE TITLE
No matching manifest for linux/amd64

### ISSUE THREAD

**Issue by linstantnoodles** [docker-library/redis#116] opened 2017-12-01 21:38 UTC
I'm trying to pull and build a redis image using the following docker compose file:
```
version: '2'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6380:6379
```

I run `docker-compose up -d redis` and I get the following output: 

```
Pulling redis (redis:latest)...
latest: Pulling from library/redis
ERROR: no matching manifest for linux/amd64 in the manifest list entries
```

There has been no changes to our compose file or docker since the last time (few weeks ago) we pulled and built this image.

**Comment by tianon** [comment] 2017-12-01 21:38
Duplicate of https://github.com/docker-library/redis/issues/114

**Comment by tianon** [comment] 2017-12-01 21:39
Doh wrong issue reference; @yosifkit maybe you can assist? /o\

**Comment by CapCap** [comment] 2017-12-01 21:46
Duplicate of #115

**Closed** 2017-12-01 21:47 UTC
