### ISSUE TITLE
Alpine version is far too big

### ISSUE THREAD

**Issue by Sirtea** [docker-library/redis#202] opened 2019-08-01 09:44 UTC
Alpine image is > 50mb, that's only half of the latest debian version.
Storage leaks come from 3 different places:

* redis binaries are not stripped
* redis-server, redis-sentinel, redis-check-rdb and redis-check-aof are the same
    * redis-sentinel is a soft link to redis-server, so the size is 0
    * redis-check-* could also be soft links, but they are not
* runDeps are installed without --no-cache flag

With this changes, I have been able to reduce image from 51.1mb to 10,3mb; here's the patch.

```bash
gerard@atlantis:~/workspace/redis/5.0/alpine$ git diff
diff --git a/5.0/alpine/Dockerfile b/5.0/alpine/Dockerfile
index 28e8808..2faf2f4 100644
--- a/5.0/alpine/Dockerfile
+++ b/5.0/alpine/Dockerfile
@@ -51,7 +51,10 @@ RUN set -ex; \
                        | sort -u \
                        | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
        )"; \
-       apk add --virtual .redis-rundeps $runDeps; \
+       apk add --no-cache --virtual .redis-rundeps $runDeps; \
+       rm /usr/local/bin/redis-check-aof && ln -s redis-server /usr/local/bin/redis-check-aof; \
+       rm /usr/local/bin/redis-check-rdb && ln -s redis-server /usr/local/bin/redis-check-rdb; \
+       strip /usr/local/bin/*; \
        apk del .build-deps; \
        \
        redis-server --version
gerard@atlantis:~/workspace/redis/5.0/alpine$ 
```

Please consider adding them to the official image.

**Comment by yosifkit** [comment] 2019-08-01 19:58
Duplicate of #180

**Comment by tianon** [comment] 2019-08-01 20:45
Added `--no-network` to `apk` invocations in https://github.com/docker-library/redis/commit/7fae90f2d9bff6e2fd36aab6a83dffcc4cce2050. :+1:

**Closed by tianon** 2019-08-01 20:45 UTC

**Comment by wglambert** [comment] 2019-08-01 22:56
Deduplicate "redis-check-aof" and "redis-check-rdb" #203
https://github.com/docker-library/redis/pull/203/commits/0b2910f292fa6ac32318cb2acc84355b11aa8a7a
